name: Alert update test

on: 
  workflow_dispatch:

jobs:
  handle-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: test
        fetch-depth: 10
    - name: Checkout zaproxy-website
      uses: actions/checkout@v2
      with:
        repository: zaproxy/zaproxy-website
        persist-credentials: false
        path: zaproxy-website
        fetch-depth: 0
    - name: Update alerts
      run: |
        pwd
        ls -l
        ls -l test/scripts/scripts
        chmod -R +w zaproxy-website/site/content/docs/alerts
        docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-live ./zap.sh -dir scripttest -addoninstallall -silent -script /zap/wrk/test/scripts/scripts/generate_alert_pages.js -cmd
        ls -l zaproxy-website/site/content/docs/alerts/
