name: Send Bluesky Post

on:
    workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1"
        id: step1
        continue-on-error: true
        run: exit 1
      - name: "Post"
        if: steps.step1.outcome != 'success'
        uses: myConsciousness/bluesky-post@v5
        with:
          text: "@psiinon.bsky.social trying conditional steps on ${{ env.Target_Name }}"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
        env:
          Target_Name: "Github Actions"
    
