name: Send Bluesky Post

on:
    workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: myConsciousness/bluesky-post@v5
        with:
          text: "@psiinon.bsky.social trying variables agin: ${{ env.Target_Name }}"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
        env:
          Target_Name: Bluesky
