
name: Baseline example.com

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Baseline example.com
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@master
        with:
          target: 'https://www.example.com/'
          docker_name: 'zaproxy/zap2docker-live'
