name: ZAP vs Firing Range TEST3

on: 
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
    steps:
    - name: Docker
      run: |
        echo $GITHUB_WORKSPACE
        sudo mkdir $GITHUB_WORKSPACE/test
        #echo "Clone zap-mgmt-scripts"
        #mkdir test
        #cd test
        #git clone https://github.com/zapbot/zap-mgmt-scripts.git
        #cd zap-mgmt-scripts/scans/firingrange
        #echo "Run scan :O"
        #/zap/wrk/zap.sh -cmd -silent -autorun /zap/test/zap-mgmt-scripts/scans/firingrange/fr-escape.yaml
