name: ZAP vs Firing Range TEST

on: 
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo "First step"
        pwd
  scan:
    needs: one
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-live
      options: --user root
      volumes:
      - /home/runner/work/test/test:/zap/wrk/:rw
    steps:
    - name: Docker
      run: |
        echo "Running in Docker?"
        pwd > /zap/wrk/test.out
  check:
    needs: scan
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo "Running in action"
        cat test.out
