name: ZAP vs Firing Range TEST2

on: 
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Docker
      run: |
        docker run --user=root -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-live /bin/bash -c "pwd > /zap/wrk/test.out"
        echo "Running in action"
        cat test.out
