name: ZAP vs Firing Range TEST2

on: 
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Docker
      run: |
        git clone https://github.com/zapbot/zap-mgmt-scripts.git
        cd zap-mgmt-scripts/scans/firingrange/
        cat fr-escape.js firing-range-score-main.js  > firing-range-score.js
        docker run --user=root -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-live zap.sh -cmd -silent -autorun /zap/wrk/fr-escape.yaml
        echo "Running in action"
        cat escape.yml
