name: ZAP vs Firing Range TEST

on: 
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
      options: -v /__w/psiinon/test:/zap/wrk/:rw
    steps:
    - name: Docker
      run: |
        echo "Running in Docker?"
        pwd > /zap/wrk/test.out
        realpath wrk/test.out
  check:
    needs: scan
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
       echo "Running in action"
        cat test.out
