name: Spider wavsep

on: 
  workflow_dispatch:

jobs:
  scan:
    runs-on: [ubuntu-latest]
    steps:
    - name: Start wavsep
      run: docker run --rm -d -p 8080:8080 owaspvwad/wavsep &
    - name: Start ZAP
      run: docker run --rm -d -p 8090:8090 --network host owasp/zap2docker-weekly zap-x.sh -daemon -host localhost -port 8090 -config "api.addrs.addr.name=.*" -config api.addrs.addr.regex=true -config api.disablekey=true &
    - name: Run ZAP API script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker run --rm --network host --env GITHUB_TOKEN=$GITHUB_TOKEN --env GITHUB_ACTOR=$GITHUB_ACTOR psiinon/zap-testing ./zap-vs-wavsep-1.5-test.sh -e 10 -n sbsb-test -t 123
