name: Misc temp test
on: 
  workflow_dispatch:

jobs:
  scan:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Do it
      run: |
        touch zap.log
        chmod a+w zap.log
        docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:nightly sh -c \
           "mkdir -p /home/zap/.mozilla/firefox/abc5jhgf.zap-client-profile/; \
           echo '[Profile0]' >> /home/zap/.mozilla/firefox/profiles.ini; \
           echo 'Name=zap-client-profile' >> /home/zap/.mozilla/firefox/profiles.ini; \
           echo 'IsRelative=1' >> /home/zap/.mozilla/firefox/profiles.ini; \
           echo 'Path=abc5jhgf.zap-client-profile' >> /home/zap/.mozilla/firefox/profiles.ini; \
           ./zap.sh -cmd -silent -addoninstall client -autorun /zap/wrk/crawl-maze.yaml; \
           cp /home/zap/.ZAP_D/zap.log /zap/wrk;"
