name: ZAP vs SSTI

on: 
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Clone this repo
      run: |
        # Setup git details
        export GITHUB_USER=psiinon
        git clone https://github.com/$GITHUB_USER/test.git
    - name: Start V2SSTI
      run: |
        docker run -d -p 127.0.0.1:5000-5100:5000-5100 -p 127.0.0.1:6000-6100:6000-6100 -w /home d10g0mrs/websites_vuln_to_ssti sh ./start_all_services.sh
    - name: Scan V2SSTI
      run: |
        cd test/ssti
        
        export file=all.yml
        # Need to do this so the zap user in docker can write to the file
        touch $file
        chmod a+w $file
        
        touch /zap/wrk/ssti-score.js
        chmod a+w /zap/wrk/ssti-score.js
        
        chmod x ssti.sh
        
        docker run -v $(pwd):/zap/wrk/:rw --network="host" owasp/zap2docker-live /zap/wrk/ssti.sh
        
        echo "--- all done?? ---"
