name: ZAP vs Webseclab

on: 
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Clone this repo
      run: |
        # Setup git details
        export GITHUB_USER=psiinon
        git clone https://github.com/$GITHUB_USER/test.git

    - name: Start Webseclab
      run: |
        docker run --add-host=host.docker.internal:host-gateway  -p 9090:9090 -i -t psiinon/webseclab /go/bin/webseclab -http=:9090 &

    - name: Scan Webseclab
      run: |
        cd test/webseclab
        # Need to do this so the zap user in docker can write to the file
        touch reflected.yml
        chmod a+w reflected.yml
        
        curl http://localhost:9090
        
        docker run -v $(pwd):/zap/wrk/:rw --add-host=host.docker.internal:host-gateway  -t owasp/zap2docker-live zap.sh -cmd -silent -autorun /zap/wrk/webseclab.yaml -config "scanner.injectable=11" -config "scanner.scanHeadersAllRequests=true"
        ls -l
        cat reflected.yml
