name: ZAP integrations tests

on: 
  workflow_dispatch:

jobs:
  scan:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: docker run --rm -t psiinon/zap2docker-tests wrk/baseline_tests.sh
